# Generated by Django 3.1 on 2020-08-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200831_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='story',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
